# Site settings
title: jcp asesores
description: "Asesoramos a empresas, autónomos y particulares en materia fiscal, laboral, contable, mercantil y RGPD."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jcpasesores.es" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero:
    hero_img: hero.jpg
    hero_title: JCP asesores
    hero_description: Asesoría integral en Alcorcón, Madrid.

# Contact form
api_token: a83cd4dd2f7789083050ca49ead542fd

# Contact info
contact:
    phone: 91 644 83 36
    email: info@jcpasesores.es
    address: Calle Cáceres 17, Bajo B Alcorcón - Madrid

# Opening hours
monday_thursday_m: 9:00 a 14:00
monday_thursday_e: 17:00 a 19:00
friday: 9:00 a 14:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Calle Cáceres, 17, Alcorcón, España
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © JCP asesores 2019

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
